### ISSUE TITLE
App shown twice

### ISSUE THREAD

**Issue by Alexander-Wilms** [jgarciao/linux-store-backend#1]
0 A.D. is shown twice at http://45.55.104.129/apps

I'm not sure if there's an issue with the manifest and the flathub.json file at https://github.com/flathub/com.play0ad.zeroad or if this is a bug in this backend.

**Comment by Alexander-Wilms** [comment]
Seems to be fixed now.

**Comment by jgarciao** [comment]
Sorry, I just saw that you reported the issue. There was a problem in the backend while obtaining the repo info. Thanks for reporting it anyway!
